build.bat

No compila ogre el script porque no sé 🗡️

Script básico para mover los .dll de ogre a bin

---

docs/BucleDeJuego.md

Diseño del bucle de juego ha sido creado

Diseño de bucle de aplicación

---

docs/CodingGuidelines.md
projects/PTSD-Core/src/main.cpp
projects/PTSD-Graphics/include/Camera.h
projects/PTSD-Graphics/include/PTSDGraphics.h
projects/PTSD-Graphics/include/Vec3.h
projects/PTSD-Graphics/src/Camera.cpp
projects/PTSD-Graphics/src/CameraImplementation.cpp
projects/PTSD-Graphics/src/CameraImplementation.h
projects/PTSD-Graphics/src/GraphicsImplementation.cpp
projects/PTSD-Graphics/src/GraphicsImplementation.h
projects/PTSD-Graphics/src/PTSDGraphics.cpp
projects/PTSD-Input/include/PTSDInput.h
projects/PTSD-Input/src/PTSDInput.cpp
projects/PTSD-Logger/include/PTSDLog.h
projects/PTSD-Logger/src/LogImpl.cpp
projects/PTSD-Logger/src/LogImpl.h
projects/PTSD-Logger/src/PTSDLog.cpp
projects/PTSD-Physics/include/PTSDPhysics.h
projects/PTSD-Physics/src/PTSDPhysics.cpp
projects/PTSD-Scripting/include/PTSDScripting.h
projects/PTSD-Scripting/src/PTSDScripting.cpp
projects/PTSD-Sound/include/PTSDSound.h
projects/PTSD-Sound/src/PTSDSound.cpp
projects/PTSD-UI/include/PTSDUI.h
projects/PTSD-UI/src/PTSDUI.cpp
vsprojects/PTSD-Graphics/PTSD-Graphics.vcxproj
vsprojects/PTSD-Graphics/PTSD-Graphics.vcxproj.filters

Aclarados algunos conceptos de los guidelines, añadidas nuevas guías y cambiado el código para reflejar estos cambios

Actualizaciones a guidelines y cambios pertinentes a código

---

projects/PTSD-Core/src/main.cpp
projects/PTSD-Scripting/include/PTSDScripting.h
projects/PTSD-Scripting/src/PTSDScripting.cpp
projects/PTSD-Scripting/src/ScriptingImplementation.cpp
projects/PTSD-Scripting/src/ScriptingImplementation.h
vsprojects/PTSD-Scripting/PTSD-Scripting.vcxproj
vsprojects/PTSD-Scripting/PTSD-Scripting.vcxproj.filters

Me he inspirado en Imagine Dragons porque es todo Smoke + Mirrors

Interfaz scripting

---

build.bat
source/Core/main.cpp
source/Graphics/include/PTSDGraphics.h
source/Physics/source/PhysicsImplementation.cpp

Está en main.cpp, para comprobar que funciona id cambiando el valor de deltaTime, cuanto mayor sea menos updates se harán por segundo y más frames se renderizarán por cada ciclo (ver el documento de diseño del bucle). Si lo ponemos en un valor muy pequeño se renderizarán menos frames por cada ciclo de update o incluso se harán varios ciclos de update por cada ciclo de renderizado.

177491505 Bucle de Juego

---

source/Sound/include/PTSDSound.h
source/Sound/include/Sound.h
source/Sound/source/PTSDSound.cpp
source/Sound/source/Sound.cpp
source/UI/include/UIImplementation.h
source/UI/source/UIImplementation.cpp

Recuerden usar const std::string& al pasar strings por parámetro.

Cambio de string por parametro a const string

---

bin/assets/scripts/Engine/Entity.lua
bin/assets/scripts/Engine/EntityManager.lua
bin/assets/scripts/Engine/EventManager.lua
bin/assets/scripts/Engine/Events/ComponentAdded.lua
bin/assets/scripts/Engine/Events/ComponentRemoved.lua
bin/assets/scripts/Engine/System.lua
bin/assets/scripts/Engine/initEngine.lua
bin/assets/scripts/Engine/test.lua
source/Scripting/source/ScriptManager.cpp

He añadido eventos básicos de componentAdded y componentRemoved, para suscribirnos a un evento solo hace falta llamar al metodo :addListener del eventManager pasandole el nombre dle evento, la entidad que suscribe y la funcion a llamar en caso de evento.
Todas las entidades vienen suscritas a los eventos componentAdded y Removed  por defecto

Eventos del ECS

---

bin/assets/scripts/Engine/test.lua
source/Input/include/InputManager.h
source/Input/source/InputImplementation.h
source/Input/source/InputManager.cpp
source/Scripting/source/ScriptManager.cpp

He cambiado el metodo de test.lua que cambia el material para que use el metodo keyJustPressed.
Shiftead y dadle a like

KeyJustPressed

---

bin/assets/scripts/Client/SystemsList.lua
build.bat
dependencies/Ogre/src/OgreMain/include/OgreSkeletonInstance.h
source/Input/include/InputManager.h
source/Input/include/PTSDkeys.h
source/Input/source/InputManager.cpp
source/Scripting/source/ScriptManager.cpp
source/UI/source/UIManager.cpp

- Build.bat ya compila nuestro motor
- Input de raton ahora detecta el frame exacto de pulsacion y soltar cada boton. **La interfaz ha cambiado porque era horrible tener un metodo para cada boton, ahora hay un metodo y le pides el boton por parametro**

Input de raton mejorado y MSBuild

---

bin/assets/scripts/Client/ComponentsList.lua
bin/assets/scripts/Client/Prefabs/Bullet.lua
bin/assets/scripts/Client/SystemsList.lua
bin/assets/scripts/Engine/EntityLoader.lua
source/Scripting/source/ScriptManager.cpp

Ahora el jugador puede disparar kirbys.
De momento el disparo es full auto because el click.
Las entidades al borrarse en lua se mantienen en cpp, la historia del delete ha sido añadida al pivotal

Disparo nave

---

source/Graphics/include/Camera.h
source/Graphics/source/Camera.cpp
source/Scripting/source/ScriptManager.cpp

Cambios necesarios para poder hacer el cambio de perspectiva en TaiFighter

Bindeo de funciones de cámara en LUA

---

source/Physics/include/PhysicsManager.h
source/Physics/source/PhysicsManager.cpp
source/Scripting/include/RigidbodyComponent.h
source/Scripting/source/RigidbodyComponent.cpp
source/Scripting/source/ScriptManager.cpp

Bastante auto-explicativos los archivos cambiados. Mi eterno agradecimiento a https://gamedev.stackexchange.com/questions/90767/bullet-physics-scaling

Cambio en ejecucion de los colliders

---

bin/assets/scripts/Engine/EntityLoader.lua
bin/assets/scripts/Engine/EntityManager.lua

Es retrocompatible y chiquito, no preocuparse

Cambio en la carga de entidades

---

bin/assets/UI/layouts/Pause.layout
bin/assets/UI/layouts/TaiFighter.layout
bin/assets/UI/test.project
bin/assets/scripts/Client/EventsList.lua
bin/assets/scripts/Client/main.lua
source/Graphics/source/GraphicsManager.cpp
source/Scripting/source/ScriptManager.cpp
source/UI/include/UIManager.h
source/UI/source/UIManager.cpp

* Ahora se puede cambiar la fuente del texto en botones
* Ahora se puede modificar el valor por codigo de la barra de progreso
* Cambiada resolucion a 1280x720 para trabajar en las UI (CEED no permitía la resolución anterior)

Extensiones para UI + quitado error de EventList.lua

---

source/Core/src/main.cpp
source/Scripting/include/ScriptManager.h
source/Scripting/source/ScriptManager.cpp

Se ha bindeado el exit para poder llamarlo desde lua y el juego sepa que tiene que cerrar

Salir de los juegos

---

tools/ToLuaScene.py

Ya no hace falta cambiar nada del script entre juegos/equipos.
- Las escenas se llamaran igual que el .blend
- Los .blend se guardan en JUEGO/assets/scenes

BlenderToLua FULL AUTO

---

build.bat

Copiados CEGUICoreWindorRenderer y CEGUIExpatParser
vaya vasilon el cegui ee

Copiados DLLs faltantes

---

bin/assets/scripts/Client/Systems/MoveSystem.lua
source/Scripting/source/ScriptManager.cpp
source/Sound/source/SoundManager.cpp

Si el primer sonido que tocabas era música saltaba un error en ejecución porque había una línea sobrante que usaba currentChannel.
CurrentChannel empieza en -1

Arreglo menor del sonido

---

bin/assets/scripts/Client/Prefabs/Bullet.lua
bin/assets/scripts/Client/Prefabs/Enemy.lua
source/Core/src/main.cpp
source/Scripting/include/ScriptManager.h
source/Scripting/source/ScriptManager.cpp

Ahora se usa deltaTime por segundos para el sistema de scripting

deltaTime utilizado

---

bin/assets/scripts/Client/main.lua
dependencies/CEGUI/src/cegui/src/DefaultLogger.cpp
dependencies/CEGUI/src/cegui/src/RendererModules/Ogre/Texture.cpp
source/Core/include/BtOgre.h
source/Core/include/CheckML.h
source/Core/src/main.cpp
source/Graphics/include/GraphicsLogger.hpp
source/Graphics/include/GraphicsManager.h
source/Graphics/source/Camera.cpp
source/Graphics/source/GraphicsManager.cpp
source/Input/source/InputManager.cpp
source/Logger/include/LogImpl.h
source/Logger/source/LogImpl.cpp
source/Physics/include/PhysicsManager.h
source/Physics/source/PhysicsManager.cpp
source/Scripting/include/Component.h
source/Scripting/include/Entity.h
source/Scripting/source/EntityManager.cpp
source/Scripting/source/RigidbodyComponent.cpp
source/Scripting/source/ScriptManager.cpp
source/Sound/source/SoundManager.cpp
source/UI/include/UIManager.h
source/UI/source/UIManager.cpp
vsprojects/PTSD-Core/PTSD.vcxproj
vsprojects/PTSD-Core/PTSD.vcxproj.filters

Después de mucho sufrimiento, ya no hay memory leaks.
Si te dice que dejas basura, tienes que recompilar CEGUI. Que tuve que cambiar el source para que no deje :D

Memory leaks

---

source/Graphics/include/GraphicsManager.h
source/Graphics/source/GraphicsManager.cpp
source/Scripting/source/ScriptManager.cpp

Ahora se puede cambiar el ambient y la orientacion de las luces desde lua

Luces configurables
